# Generated by Django 5.0.7 on 2024-07-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_notification_sender_alter_notification_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
