# Generated by Django 5.0.7 on 2024-07-13 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_notification_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='post_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
    ]
